target 'CJWVideoListPlay' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CJWVideoListPlay
	pod 'AFNetworking', '~> 3.0'
	pod 'SDWebImage'
	pod 'KSYMediaPlayer_iOS', :git => 'https://github.com/ksvc/KSYMediaPlayer_iOS.git'
end